### ISSUE TITLE
List of dates are not date objects any more after update

### ISSUE THREAD

**Issue by Matthijz98** [adamghill/django-unicorn#514] opened 2023-02-23 20:15 UTC
I am trying to make a table based on the dates in an list.
The init function makes a list of date objects and i use that to show them in the cells of the table
But after a click event that triggers the ``select_date()`` function my array of dates are now str dates this is a problem because I can not format these dates. I could write a custom template tag but that should not be needed right?

My striped down code
```
class BbrsCalendarView(UnicornView):
    dates = []

    def __init__(self, *args, **kwargs):
        super().__init__(**kwargs)
        
        for x in range(3):
            self.dates.append(start_day + timedelta(days=x))

        print(self.dates)  // [datetime.date(2023, 2, 23), datetime.date(2023, 2, 24), datetime.date(2023, 2, 25)]

    def select_date(self, date, boat_id):
        print(self.dates) // ['2023-02-23', '2023-02-24', '2023-02-25']

```

**Comment by adamghill** [comment] 2023-02-24 15:33
`dates` gets serialized to strings for the JSON to store the data and then deserialized when the action happens. For `datetime` I try to make this seamless (as mentioned [here](https://github.com/adamghill/django-unicorn/blob/5e0e87b8bb26d2bdbba4f89e520cac04aaec0bd6/docs/source/actions.md?plain=1#L82)), but I might need to add support for `date`.

Another option that _might_ work would try adding a type to `dates`? Something like:

```python
from typing import List
from datetime import date

class BbrsCalendarView(UnicornView):
    dates: List[date] = []

    ...
```

When `Unicorn` sees a type annotation it tries to coerce the string into the correct type, but I'm not positive this will work for `date`.

I could also look into adding explicit support for `date` if that would be helpful for you.

**Comment by Matthijz98** [comment] 2023-06-28 12:56
This problem keeps coming up.
The solution above does not work i made a quick work around but that keep breaking other stuff.
Would be nice to see date and datetime supported.

To give a bit more details what is the problem.
I am trying to make a calendar where you can select dates.
```
{% for row_date in row_dates %}
        <td unicorn:click="select_date('{{ row_date|date:'c' }}')"
            {{ row_date|date:'c' }}
        </td>
    {% endfor %}
```

```
class CalendarRowView(UnicornView):
    selected_dates: List[date] = []
    row_dates: List[date] = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.row_dates = kwargs.get('dates')

    def select_date(self, date):
        print(self.row_dates)
        print(date)
        print(self.selected_dates)
        if date in self.selected_dates:
            print('removing date')
            self.selected_dates.remove(date)
        else:
            self.selected_dates.append(date)
        print(self.selected_dates)
 ```
The first load works fine and the table looks fine:
![image](https://github.com/adamghill/django-unicorn/assets/17087153/5f90aff5-a45c-4fc0-a81a-a71055bd3c14)
But after clicking a cell the date becomes a string for the template and the date format functions stop working in the template and the component.

**Comment by adamghill** [comment] 2023-06-28 20:29
Does the `date:'c'` in `select_date('{{ row_date|date:'c' }}` convert row_date to a string? Maybe I missed something, but does it work without the date filter?

**Comment by winrid** [comment] 2023-06-30 07:49
I am also running into this as a model used in my view has `start_date.day` in `__str()__` - this causes the view to blow up even though I don't print the said model anywhere in the template.

**Comment by winrid** [comment] 2023-07-01 06:27
Note that it also breaks using dates - datetimes - anywhere in a model:

```
    end_date = models.DateTimeField()
    def is_finalized(self):
        return self.end_date < timezone.now()
```

Gives:

```
TypeError: '<' not supported between instances of 'str' and 'datetime.datetime'
```

**Comment by Matthijz98** [comment] 2023-07-05 17:59
> Does the `date:'c'` in `select_date('{{ row_date|date:'c' }}` convert row_date to a string? Maybe I missed something, but does it work without the date filter?

I tryed it without the date filter but that does not change anything

**Comment by adamghill** [comment] 2023-08-09 02:48
https://github.com/adamghill/django-unicorn/pull/571 provides the ability to add type annotations to action method args/kwargs and `Unicorn` will attempt to coerce the value into the type hint. I need to do a little more testing, but hopefully this will solve this use case.

**Comment by adamghill** [comment] 2023-08-11 02:43
#571 has been merged into `main` and will be in 0.54.0. Closing this, but let me know if you run into problems once the new version is published.

**Closed by adamghill** 2023-08-11 02:43 UTC

**Comment by winrid** [comment] 2023-10-19 00:11
@adamghill Sorry to say this is still an issue in 0.56:

```
    if self.end_date is None or self.start_date.day == self.end_date.day:
AttributeError: 'str' object has no attribute 'day'
```

Caused by:

```
    def __str__(self):
        result = ""
        if self.name is not None:
            result += self.name
        if self.start_date is not None:
            if self.end_date is None or self.start_date.day == self.end_date.day:
                # save cognitive load when reading
                result += " " + self.start_date.__format__("%m/%d/%Y")
            else:
                result += f' {self.start_date.__format__("%m/%d/%Y")} → {self.end_date.__format__("%m/%d/%Y")}'
        return result
```

Would it be helpful if I just invited you to the project so you can check it yourself? since we're a pretty heavy user of Unicorn.

Seems to only happen when I call a method from the template like on change:

```
<select unicorn:model="selected_year" unicorn:change="render_events()">
```

My view has:

```
class FindEventsView(UnicornView):
    events: list[Event] = None
```

and render_events is:

```
    def render_events(self):
        query = Event.objects.filter(verified=True, start_date__year=self.selected_year['year'])
        now = timezone.now()
        query = query.filter(
            Q(registration_status=Event.RegistrationStatus.OPEN) | Q(registration_status=Event.RegistrationStatus.AUTO,
                                                                     start_date__gte=now))
        self.events = query.all().order_by('start_date')
```

**Comment by adamghill** [comment] 2023-10-19 00:40
>Would it be helpful if I just invited you to the project so you can check it yourself

@winrid Yes, please! Having something I can mess with would be very helpful. Thanks!

**Comment by winrid** [comment] 2023-10-19 03:09
@adamghill I've invited you. Also, feel free to add me on Discord: happyhydra

**Comment by winrid** [comment] 2023-12-28 08:44
@adamghill This is still an issue:

```
Internal Server Error: /unicorn/message/organizer_event_edit
Traceback (most recent call last):
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "<decorator-gen-25>", line 2, in message
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/decorators.py", line 20, in timed
    result = func(*args, **kwargs)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/views/__init__.py", line 49, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/views/__init__.py", line 554, in message
    json_result = _handle_component_request(request, component_request)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/views/__init__.py", line 407, in _handle_component_request
    return _process_component_request(request, component_request)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/views/__init__.py", line 105, in _process_component_request
    set_property_from_data(component, property_name, property_value)
  File "<decorator-gen-23>", line 2, in set_property_from_data
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/decorators.py", line 20, in timed
    result = func(*args, **kwargs)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/views/utils.py", line 68, in set_property_from_data
    component_or_field._set_property(name, value, call_updating_method=True, call_updated_method=False)
  File "<decorator-gen-15>", line 2, in _set_property
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/decorators.py", line 20, in timed
    result = func(*args, **kwargs)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/components/unicorn_view.py", line 629, in _set_property
    form = self._get_form(data)
  File "<decorator-gen-9>", line 2, in _get_form
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django_unicorn/decorators.py", line 27, in timed
    arguments = f"{args}, "
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django/db/models/query.py", line 377, in __repr__
    return "<%s %r>" % (self.__class__.__name__, data)
  File "/home/winrid/dev/sidewaysdatadotcom/venv/lib/python3.10/site-packages/django/db/models/base.py", line 588, in __repr__
    return "<%s: %s>" % (self.__class__.__name__, self)
  File "/home/winrid/dev/sidewaysdatadotcom/sidewaysdata/models/event.py", line 80, in __str__
    if self.end_date is None or self.start_date.day == self.end_date.day:
AttributeError: 'str' object has no attribute 'day'
```

model:

```
    start_date: timezone.datetime = models.DateTimeField()
    end_date: timezone.datetime = models.DateTimeField()
```

I think it's something to do with:

```
                <select unicorn:model="copy_event_from">
                    {% for event in my_events %}
                        <option value="{{ event.id }}">{{ event }}</option>
                    {% endfor %}
                </select>
```
