### ISSUE TITLE
mount() called every request

### ISSUE THREAD

**Issue by citizenfish** [adamghill/django-unicorn#596] opened 2023-09-11 15:17 UTC
I have a component in a template which I pass a file_id to as follows:-

```html
{% extends 'base.html' %}
{% load static unicorn %}
{% block content %}
    {% csrf_token %}
    {% unicorn 'file_details' file_id=selected %}
{% endblock %}
```

**selected** is a variable in the context

The component has a method mount() that looks up this file_id in the database

```python
    def mount(self):
        self.file_id = self.component_kwargs["file_id"]
```

The template **file_details** has various interactions with the component using Unicorn:model and Unicorn:click

When I run this locally everything works perfectly. mount() is called once and the subsequent calls have access to the file_id

But when I deploy to AWS lightsail the behaviour changes. mount() is called by every single interaction and fails becuase **component_kwargs** does not contain the key **file_id**

This is clearly down to our deployment. But could you shed any light on what might be causing this behaviour. Our environment is load balanced so we probably need to do something to cope with requests going to separate cluster instances

**Comment by adamghill** [comment] 2023-09-11 22:51
I'm curious what you have set up for `CACHES` in your settings file? `Unicorn` uses the cache to store component data and I wonder if you have the default local memory storage and that is causing a problem. I use a shared `redis` as my cache so I've never run into a problem with multiple servers.

**Comment by citizenfish** [comment] 2023-09-12 08:06
We don't have any specific setting for CACHES, just using defaults. We were running django using gnuicorn as follows:-

```bash
gunicorn --bind 0.0.0.0:80 \
--workers=4 \
--timeout 120 \
--log-level info locaria.wsgi:application \
--access-logfile '-'
```

We found that reducing the number of workers to 1 fixed the problem but it would be good to understand how we can code round this as running mount every transaction is going to be very inefficient for us.

**Comment by adamghill** [comment] 2023-09-12 12:03
Gunicorn workers each have their own memory so the [default local memory cache](https://docs.djangoproject.com/en/4.2/topics/cache/#local-memory-caching) is not shared across workers.

If you only have one server, but multiple workers you could use [filesystem caching](https://docs.djangoproject.com/en/4.2/topics/cache/#filesystem-caching). If you have multiple servers you will need one of these:
- [database caching](https://docs.djangoproject.com/en/4.2/topics/cache/#database-caching)
- [redis caching](https://docs.djangoproject.com/en/4.2/topics/cache/#redis)
- [memcache caching](https://docs.djangoproject.com/en/4.2/topics/cache/#memcached)

I tend to use redis so in all of my projects I have something like this:
```python
# settings.py

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://some-redis-server-host:6379",
    }
}
```

I'm going to look into some potential workarounds to prevent `mount` from being called, but not having a shared cache will negatively impact other functionality, especially related to child/parent components (see #593 for another example).

Sorry this is not clearly stated in the documentation as a requirement for a production deployment -- I'm going to update the docs to make this more explicit.

**Comment by imankulov** [comment] 2023-09-12 19:55
Thank you for your response. I can confirm that having a persistent cache solves the issue. I agree that explicitly outlining the role of the cache in the system would be very helpful. Other than this, I think the issue can be closed, as it's not a bug, but rather the system working as intended in the current architecture.

**Comment by adamghill** [comment] 2023-10-02 02:30
@citizenfish Were you able to use a shared cache to see if this problem went away? Let me know if you still have problems otherwise, I'll close this issue in a few days. Thanks!

**Comment by citizenfish** [comment] 2023-10-02 11:47
Yes it did work. Apologies I should have updated the issue. Thanks

**Comment by adamghill** [comment] 2023-10-02 12:08
That's great news! I updated https://www.django-unicorn.com/docs/installation/ to mention setting up cache for production deployments. Closing this issue, but let me know if other changes would be helpful.

**Closed by adamghill** 2023-10-02 12:08 UTC

**Comment by Yethiel** [comment] 2024-01-29 11:09
> That's great news! I updated https://www.django-unicorn.com/docs/installation/ to mention setting up cache for production deployments. Closing this issue, but let me know if other changes would be helpful.

The docs don't seem to mention it yet.
I ran into the same issue: Locally everything works fine but on production everything was very buggy and unpredictable. 

I'm glad it's only a cache issue, unicorn has been great so far! I enabled file based caching and now it works beautifully.
